#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMSReports
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="OMS")]
	public partial class toSQLDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    #endregion
		
		public toSQLDataContext() : 
				base(global::OMSReports.Properties.Settings.Default.OMSConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public toSQLDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public toSQLDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public toSQLDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public toSQLDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<RegistryBase> RegistryBase
		{
			get
			{
				return this.GetTable<RegistryBase>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RegistryBase")]
	public partial class RegistryBase
	{
		
		private string _hist_nom;
		
		private string _dat_post;
		
		private string _dat_wypis;
		
		private string _name_1;
		
		private string _name_2;
		
		private string _name_3;
		
		private string _pol;
		
		private string _dat_born;
		
		private string _mkb1;
		
		private string _rab_place;
		
		private string _otdel;
		
		private string _polis_ser;
		
		private string _polis_num;
		
		private string _company;
		
		private string _rezult;
		
		private string _region;
		
		private string _lpu_napr;
		
		private string _full_sum;
		
		private string _dat_reestr;
		
		private string _sum1;
		
		private string _spr_soc;
		
		private string _ident_m;
		
		private string _subject;
		
		private string _pasp_num;
		
		private string _pasp_ser;
		
		private string _napr_num;
		
		private string _napr_dat;
		
		private string _mr;
		
		private string _wid_prof;
		
		private string _c_doc;
		
		private string _kladr;
		
		private string _cel;
		
		private string _date_n;
		
		private string _date_e;
		
		private string _cod_usl;
		
		private string _profil;
		
		private string _vpolis;
		
		private string _oper_cnt;
		
		private string _vidp_amb;
		
		private string _napr_type;
		
		private string _id_vmp;
		
		private string _napr_dir;
		
		private string _fl_stm;
		
		private string _spr_lgt;
		
		private string _spr_invld;
		
		private string _enp;
		
		private string _administrator;
		
		private string _mo;
		
		private string _usl_krat;
		
		private string _add_dat;
		
		public RegistryBase()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hist_nom", DbType="NVarChar(MAX)")]
		public string hist_nom
		{
			get
			{
				return this._hist_nom;
			}
			set
			{
				if ((this._hist_nom != value))
				{
					this._hist_nom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dat_post", DbType="NVarChar(MAX)")]
		public string dat_post
		{
			get
			{
				return this._dat_post;
			}
			set
			{
				if ((this._dat_post != value))
				{
					this._dat_post = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dat_wypis", DbType="NVarChar(MAX)")]
		public string dat_wypis
		{
			get
			{
				return this._dat_wypis;
			}
			set
			{
				if ((this._dat_wypis != value))
				{
					this._dat_wypis = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_1", DbType="NVarChar(MAX)")]
		public string name_1
		{
			get
			{
				return this._name_1;
			}
			set
			{
				if ((this._name_1 != value))
				{
					this._name_1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_2", DbType="NVarChar(MAX)")]
		public string name_2
		{
			get
			{
				return this._name_2;
			}
			set
			{
				if ((this._name_2 != value))
				{
					this._name_2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_3", DbType="NVarChar(MAX)")]
		public string name_3
		{
			get
			{
				return this._name_3;
			}
			set
			{
				if ((this._name_3 != value))
				{
					this._name_3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pol", DbType="NVarChar(MAX)")]
		public string pol
		{
			get
			{
				return this._pol;
			}
			set
			{
				if ((this._pol != value))
				{
					this._pol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dat_born", DbType="NVarChar(MAX)")]
		public string dat_born
		{
			get
			{
				return this._dat_born;
			}
			set
			{
				if ((this._dat_born != value))
				{
					this._dat_born = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mkb1", DbType="NVarChar(MAX)")]
		public string mkb1
		{
			get
			{
				return this._mkb1;
			}
			set
			{
				if ((this._mkb1 != value))
				{
					this._mkb1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rab_place", DbType="NVarChar(MAX)")]
		public string rab_place
		{
			get
			{
				return this._rab_place;
			}
			set
			{
				if ((this._rab_place != value))
				{
					this._rab_place = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_otdel", DbType="NVarChar(MAX)")]
		public string otdel
		{
			get
			{
				return this._otdel;
			}
			set
			{
				if ((this._otdel != value))
				{
					this._otdel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_polis_ser", DbType="NVarChar(MAX)")]
		public string polis_ser
		{
			get
			{
				return this._polis_ser;
			}
			set
			{
				if ((this._polis_ser != value))
				{
					this._polis_ser = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_polis_num", DbType="NVarChar(MAX)")]
		public string polis_num
		{
			get
			{
				return this._polis_num;
			}
			set
			{
				if ((this._polis_num != value))
				{
					this._polis_num = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_company", DbType="NVarChar(MAX)")]
		public string company
		{
			get
			{
				return this._company;
			}
			set
			{
				if ((this._company != value))
				{
					this._company = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rezult", DbType="NVarChar(MAX)")]
		public string rezult
		{
			get
			{
				return this._rezult;
			}
			set
			{
				if ((this._rezult != value))
				{
					this._rezult = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_region", DbType="NVarChar(MAX)")]
		public string region
		{
			get
			{
				return this._region;
			}
			set
			{
				if ((this._region != value))
				{
					this._region = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lpu_napr", DbType="NVarChar(MAX)")]
		public string lpu_napr
		{
			get
			{
				return this._lpu_napr;
			}
			set
			{
				if ((this._lpu_napr != value))
				{
					this._lpu_napr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_full_sum", DbType="NVarChar(MAX)")]
		public string full_sum
		{
			get
			{
				return this._full_sum;
			}
			set
			{
				if ((this._full_sum != value))
				{
					this._full_sum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dat_reestr", DbType="NVarChar(MAX)")]
		public string dat_reestr
		{
			get
			{
				return this._dat_reestr;
			}
			set
			{
				if ((this._dat_reestr != value))
				{
					this._dat_reestr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sum1", DbType="NVarChar(MAX)")]
		public string sum1
		{
			get
			{
				return this._sum1;
			}
			set
			{
				if ((this._sum1 != value))
				{
					this._sum1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_spr_soc", DbType="NVarChar(MAX)")]
		public string spr_soc
		{
			get
			{
				return this._spr_soc;
			}
			set
			{
				if ((this._spr_soc != value))
				{
					this._spr_soc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ident_m", DbType="NVarChar(MAX)")]
		public string ident_m
		{
			get
			{
				return this._ident_m;
			}
			set
			{
				if ((this._ident_m != value))
				{
					this._ident_m = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subject", DbType="NVarChar(MAX)")]
		public string subject
		{
			get
			{
				return this._subject;
			}
			set
			{
				if ((this._subject != value))
				{
					this._subject = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pasp_num", DbType="NVarChar(MAX)")]
		public string pasp_num
		{
			get
			{
				return this._pasp_num;
			}
			set
			{
				if ((this._pasp_num != value))
				{
					this._pasp_num = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pasp_ser", DbType="NVarChar(MAX)")]
		public string pasp_ser
		{
			get
			{
				return this._pasp_ser;
			}
			set
			{
				if ((this._pasp_ser != value))
				{
					this._pasp_ser = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_napr_num", DbType="NVarChar(MAX)")]
		public string napr_num
		{
			get
			{
				return this._napr_num;
			}
			set
			{
				if ((this._napr_num != value))
				{
					this._napr_num = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_napr_dat", DbType="NVarChar(MAX)")]
		public string napr_dat
		{
			get
			{
				return this._napr_dat;
			}
			set
			{
				if ((this._napr_dat != value))
				{
					this._napr_dat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mr", DbType="NVarChar(MAX)")]
		public string mr
		{
			get
			{
				return this._mr;
			}
			set
			{
				if ((this._mr != value))
				{
					this._mr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wid_prof", DbType="NVarChar(MAX)")]
		public string wid_prof
		{
			get
			{
				return this._wid_prof;
			}
			set
			{
				if ((this._wid_prof != value))
				{
					this._wid_prof = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_doc", DbType="NVarChar(MAX)")]
		public string c_doc
		{
			get
			{
				return this._c_doc;
			}
			set
			{
				if ((this._c_doc != value))
				{
					this._c_doc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kladr", DbType="NVarChar(MAX)")]
		public string kladr
		{
			get
			{
				return this._kladr;
			}
			set
			{
				if ((this._kladr != value))
				{
					this._kladr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cel", DbType="NVarChar(MAX)")]
		public string cel
		{
			get
			{
				return this._cel;
			}
			set
			{
				if ((this._cel != value))
				{
					this._cel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_n", DbType="NVarChar(MAX)")]
		public string date_n
		{
			get
			{
				return this._date_n;
			}
			set
			{
				if ((this._date_n != value))
				{
					this._date_n = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_e", DbType="NVarChar(MAX)")]
		public string date_e
		{
			get
			{
				return this._date_e;
			}
			set
			{
				if ((this._date_e != value))
				{
					this._date_e = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_usl", DbType="NVarChar(MAX)")]
		public string cod_usl
		{
			get
			{
				return this._cod_usl;
			}
			set
			{
				if ((this._cod_usl != value))
				{
					this._cod_usl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_profil", DbType="NVarChar(MAX)")]
		public string profil
		{
			get
			{
				return this._profil;
			}
			set
			{
				if ((this._profil != value))
				{
					this._profil = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vpolis", DbType="NVarChar(MAX)")]
		public string vpolis
		{
			get
			{
				return this._vpolis;
			}
			set
			{
				if ((this._vpolis != value))
				{
					this._vpolis = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_oper_cnt", DbType="NVarChar(MAX)")]
		public string oper_cnt
		{
			get
			{
				return this._oper_cnt;
			}
			set
			{
				if ((this._oper_cnt != value))
				{
					this._oper_cnt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vidp_amb", DbType="NVarChar(MAX)")]
		public string vidp_amb
		{
			get
			{
				return this._vidp_amb;
			}
			set
			{
				if ((this._vidp_amb != value))
				{
					this._vidp_amb = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_napr_type", DbType="NVarChar(MAX)")]
		public string napr_type
		{
			get
			{
				return this._napr_type;
			}
			set
			{
				if ((this._napr_type != value))
				{
					this._napr_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_vmp", DbType="NVarChar(MAX)")]
		public string id_vmp
		{
			get
			{
				return this._id_vmp;
			}
			set
			{
				if ((this._id_vmp != value))
				{
					this._id_vmp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_napr_dir", DbType="NVarChar(MAX)")]
		public string napr_dir
		{
			get
			{
				return this._napr_dir;
			}
			set
			{
				if ((this._napr_dir != value))
				{
					this._napr_dir = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fl_stm", DbType="NVarChar(MAX)")]
		public string fl_stm
		{
			get
			{
				return this._fl_stm;
			}
			set
			{
				if ((this._fl_stm != value))
				{
					this._fl_stm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_spr_lgt", DbType="NVarChar(MAX)")]
		public string spr_lgt
		{
			get
			{
				return this._spr_lgt;
			}
			set
			{
				if ((this._spr_lgt != value))
				{
					this._spr_lgt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_spr_invld", DbType="NVarChar(MAX)")]
		public string spr_invld
		{
			get
			{
				return this._spr_invld;
			}
			set
			{
				if ((this._spr_invld != value))
				{
					this._spr_invld = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enp", DbType="NVarChar(MAX)")]
		public string enp
		{
			get
			{
				return this._enp;
			}
			set
			{
				if ((this._enp != value))
				{
					this._enp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_administrator", DbType="NVarChar(MAX)")]
		public string administrator
		{
			get
			{
				return this._administrator;
			}
			set
			{
				if ((this._administrator != value))
				{
					this._administrator = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mo", DbType="NVarChar(MAX)")]
		public string mo
		{
			get
			{
				return this._mo;
			}
			set
			{
				if ((this._mo != value))
				{
					this._mo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usl_krat", DbType="NVarChar(MAX)")]
		public string usl_krat
		{
			get
			{
				return this._usl_krat;
			}
			set
			{
				if ((this._usl_krat != value))
				{
					this._usl_krat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_add_dat", DbType="NVarChar(MAX)")]
		public string add_dat
		{
			get
			{
				return this._add_dat;
			}
			set
			{
				if ((this._add_dat != value))
				{
					this._add_dat = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
